### ISSUE TITLE
Update DG with individual enhancements

### ISSUE THREAD

**Issue by hansstanley** [AY2223S2-CS2103T-F12-3/tp#135]
Due Mar 24 (Friday) 1.59pm (before lecture)

> Each member should describe the implementation of at least one enhancement she has added (or planning to add).
Expected length: 1+ page per person

> The description can contain things such as,
> * How the feature is implemented (or is going to be implemented).
> * Why it is implemented that way.
> * Alternatives considered.

Individual enhancements (to be converted into issues):

* [x] @igezt : `add` and `edit` commands, Storage and Model
* [x] @hansstanley : `tab` command and UI
* [x] @Shuggan : proposed features, can help Nic
* [x] @nicljr : `addevent`, `fav` and `unfav` commands
* [x] @rachtan27 : `select` command

**Comment by igezt** [comment]
This looks like it was done quite awhile ago. So ill just close it first.
