### ISSUE TITLE
[PE-D][Tester E] Wrong syntax for ‘find’ in user guide 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-F12-3/tp#208]
Additional KEYWORD in syntax when the actual syntax is ‘find PREFIX/KEYWORDS…’
![Finding Particular Contacts find.png](https://raw.githubusercontent.com/tangyuantyy/ped/main/files/49d8105e-7148-44af-8a96-8f8cb11800f3.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: tangyuantyy/ped#1

**Comment by hansstanley** [comment]
Duplicated of #227
