### ISSUE TITLE
[PE-D][Tester E] Error message not specific to mode

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-F12-3/tp#210]
The error message displayed is not specific to Events mode and it does not match the error. Better error message can be made for each mode.

![Events.png](https://raw.githubusercontent.com/tangyuantyy/ped/main/files/6c28f284-bae3-4742-8ca3-511027810ac3.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: tangyuantyy/ped#3

**Comment by hansstanley** [comment]
Won't fix; wrong usage of command.
