### ISSUE TITLE
[PE-D][Tester B] Add Event bug

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-F12-3/tp#234]
even when an invalid date is entered, it allows it and reformats the date even though it is an invalid date.

---
![Screenshot 2023-03-31 at 2.56.38 PM.png](https://raw.githubusercontent.com/SeeuSim/ped/main/files/dc544fc7-52c7-4c9a-8a9d-be4d1f0a809a.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: SeeuSim/ped#11

**Comment by igezt** [comment]
We can argue that the user will want to remember dates from the past. Events is not just a calendar for the future but the past as well.

**Comment by hansstanley** [comment]
I think the tester is saying how nonexistent calendar dates get bumped down, for e.g.:
* `2023-02-29 -> 2023-02-28`
* `2023-02-30 -> 2023-02-28`
* `2023-04-31 -> 2023-04-30`

Perhaps this behaviour was desirable in the design of `LocalDateTime#parse`, hence I think we should describe this edge case in the UG.

**Comment by nicljr** [comment]
So is it in this case, as 1999 is not a leap year Feb shouldnt have 29 Days. We are gonna document this as an edge case in our UG right?

**Comment by igezt** [comment]
> So is it in this case, as 1999 is not a leap year Feb shouldnt have 29 Days. We are gonna document this as an edge case in our UG right?

Yep I think we can add this under things to note for the AddEvent command
