### ISSUE TITLE
Extra prefixes in commands are not recognised as invalid format

### ISSUE THREAD

**Issue by hansstanley** [AY2223S2-CS2103T-F12-3/tp#274]
The error message is targeted at the previous prefix instead of showing the command usage.

<img width="978" alt="Screenshot 2023-04-06 at 17 33 40" src="https://user-images.githubusercontent.com/20805849/230336740-10eb69ba-e235-400d-93cd-6a8b903be885.png">

<img width="978" alt="Screenshot 2023-04-06 at 17 33 54" src="https://user-images.githubusercontent.com/20805849/230336811-8654128a-b42a-464f-bf9b-c80d2a3d38b0.png">

<img width="978" alt="Screenshot 2023-04-06 at 17 34 27" src="https://user-images.githubusercontent.com/20805849/230336966-6649dd34-dbb5-4e80-a910-67d5b85c606d.png">

**Comment by igezt** [comment]
For future features

**Comment by igezt** [comment]
Merged into #299
