### ISSUE TITLE
inform users that if multiple same fields are specified, only latest one would be acccepted

### ISSUE THREAD

**Issue by rachtan27** [AY2223S2-CS2103T-F12-3/tp#275]
addevent d/Dinner with Family s/2023-03-30 1600 e/2023-03-30 1800 s/2023-03-30 1900 e/2023-03-30 2359 d/sleep

valid input >> 
![image](https://user-images.githubusercontent.com/100123345/230338682-d89b7477-bd7a-42bc-be20-c0a4a7506606.png)

**Comment by igezt** [comment]
Add line to UG to say that "Only last input for a prefix is taken, unless it is for a FieldGroup"

**Comment by igezt** [comment]
Merged into Issue #298
