### ISSUE TITLE
User shows tags and favourite information

### ISSUE THREAD

**Issue by hansstanley** [AY2223S2-CS2103T-F12-3/tp#281]
* `Tags` and `Favorite` show in the result message of `edituser`
  <img width="978" alt="Screenshot 2023-04-06 at 18 04 16" src="https://user-images.githubusercontent.com/20805849/230345101-873b3c0a-4f75-46cf-af2a-4c69becf5f5d.png">
* `edituser t/something` is a valid command even though tags are not applicable to User

**Comment by igezt** [comment]
Merged into #299
