### ISSUE TITLE
Chinese Character handling

### ISSUE THREAD

**Issue by nicljr** [AY2223S2-CS2103T-F12-3/tp#287]
Contacts cannot handle chinese characters but adding event can handle chinese characters 
![image](https://user-images.githubusercontent.com/99934908/230348525-4c39200a-ff74-47e4-aa94-80215882baec.png)

so maybe we can say that contacts handles han yi pin ?

**Comment by igezt** [comment]
Future Features: Other langauge compatibility

**Comment by igezt** [comment]
Merged into #299
