### ISSUE TITLE
Add attributes for popular communication channels to Person class

### ISSUE THREAD

**Issue by hansstanley** [AY2223S2-CS2103T-F12-3/tp#6]
As a student who likes fast replies, I want to know other students’ favored communication, so that I can increase my chances of getting a quick reply.

E.g. of popular communication channels:
- Telegram
- WhatsApp
- Instagram
- Facebook
- Slack
- Discord
- Snapchat
- Zoom
- School email
- Messenger owl
- Telepathy

**Comment by igezt** [comment]
Closed with the new PR. Currently allows users to input any communication channel. Still need to decide if we want to restrict their options
