### ISSUE TITLE
Add contact categorisation

### ISSUE THREAD

**Issue by hansstanley** [AY2223S2-CS2103T-F12-3/tp#8]
As a student who often contacts external organisations, I want to segregate my contacts into different categories (e.g. friends, family, t-shirt suppliers, bus drivers , sponsors etc.), so that I can organise my contacts effectively.

E.g. of categories:
- Friends
- Family
- Vendors
- Drivers
- Sponsors
- Professors
- CS Gods

**Comment by igezt** [comment]
For now, Ill KIV this and maybe add it in with other fields for v1.3 instead

**Comment by igezt** [comment]
Closed because this overlaps with the enhanced find command and tags
Issue #109
